Update tools.

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,10 +1,17 @@
 #!/bin/bash
+if [ `$(dirname $0)/countstr groups docker` != 1 ];then
+ echo "Couldn't run docker.Abort.">&2
+exit
+fi
+#import configuration.
+source ../tools/conf
+
 #Build
 #precise
 ../tools/importer \
 precise \
 ubuntu \
-0.1.1 \
+${source_version[0]} \
 "cp $PROJECT/patches/0001-patch-for-precise.patch /mnt" \
 "cd purple-line&&patch -p1 < /mnt/0001-patch-for-precise.patch&&cd /" \
 "rm -rf /mnt/0001-patch-for-precise.patch" \
@@ -13,7 +20,7 @@ ubuntu \
 ../tools/importer \
 sid \
 debian \
-0.1.1 \
+${source_version[0]} \
 "cp $PROJECT/patches/0001-change-build-dep.patch /mnt" \
 "cd thrift-1.0.0&&patch -p1 < /mnt/0001-change-build-dep.patch&&cd /" \
 "rm -rf /mnt/0001-change-build-dep.patch" \
@@ -22,7 +29,7 @@ debian \
 ../tools/importer \
 stable \
 debian \
-0.1.1 \
+${source_version[0]} \
 "cp $PROJECT/patches/0001-change-build-dep.patch /mnt" \
 "cd thrift-1.0.0&&patch -p1 < /mnt/0001-change-build-dep.patch&&cd /" \
 "rm -rf /mnt/0001-change-build-dep.patch" \
@@ -31,7 +38,7 @@ debian \
 ../tools/importer \
 trusty \
 ubuntu \
-0.1.1 \
+${source_version[0]} \
 "cp $PROJECT/patches/0001-change-build-dep.patch /mnt" \
 "cd thrift-1.0.0&&patch -p1 < /mnt/0001-change-build-dep.patch&&cd /" \
 "rm -rf /mnt/0001-change-build-dep.patch" \
@@ -40,7 +47,7 @@ ubuntu \
 ../tools/importer \
 vivid \
 ubuntu \
-0.1.1 \
+${source_version[0]} \
 "cp $PROJECT/patches/0001-change-build-dep.patch /mnt" \
 "cd thrift-1.0.0&&patch -p1 < /mnt/0001-change-build-dep.patch&&cd /" \
 "rm -rf /mnt/0001-change-build-dep.patch" \
@@ -49,17 +56,18 @@ ubuntu \
 ../tools/importer \
 wily \
 ubuntu \
-0.1.1 \
+${source_version[0]} \
 "cp $PROJECT/patches/0001-change-build-dep.patch /mnt" \
 "cd thrift-1.0.0&&patch -p1 < /mnt/0001-change-build-dep.patch&&cd /" \
 "rm -rf /mnt/0001-change-build-dep.patch" \
 
-update precise
-update sid
-update stable
-update trusty
-update vivid
-update wily
-installer purple-line
-installer thrift
-pushto
+
+../tools/update precise
+../tools/update sid
+../tools/update stable
+../tools/update trusty
+../tools/update vivid
+../tools/update wily
+../tools/installer purple-line
+../tools/installer thrift
+../tools/pushto
